export const ProductContentItems = [
  {
    image: '/content/NorsupP13X.webp',
    pageLink: 'NorsupP13X',
    type: 'Product',
    category: 'Heater pump',
    price: 2899.0,
    description:
      'Perfect for small to medium-sized pools, the Norsup P13X provides efficient and reliable heating with a compact footprint. With a power output of 13 kW, it’s designed to deliver excellent performance while keeping energy consumption low, thanks to its inverter technology and eco-friendly R32 refrigerant.',
    specifications: [
      { name: 'Heating Capacity', value: '13 kW' },
      { name: 'Power Supply', value: '230V/50Hz (Single-phase)' },
      { name: 'COP', value: 'Up to 13 (depending on conditions)' },
      { name: 'Operating Temperature Range', value: '-15°C to +40°C' },
      { name: 'Refrigerant', value: 'Eco-friendly R32' },
      { name: 'Noise Level', value: '40-46 dB(A)' },
      { name: 'Heat Exchanger', value: 'Titanium' },
      { name: 'Compressor Type', value: 'Inverter Compressor' },
      { name: 'Control Interface', value: 'LCD Touch Screen' },
      { name: 'Dimensions', value: '900mm x 350mm x 630mm' },
      { name: 'Weight', value: '58 kg' },
      { name: 'Flow Rate', value: '3.5-4.0 m³/h' },
      { name: 'Wi-Fi Connectivity', value: 'Yes' },
      { name: 'Defrosting System', value: 'Reverse Cycle Defrosting' },
      {
        name: 'Warranty',
        value: '2 years product, 5 years compressor and heat exchanger',
      },
    ],
    feature: true,
    hidden: false,
  },
  {
    image: '/content/NorsupP13X.webp',
    pageLink: 'NorsupP17X',
    type: 'Product',
    category: 'Heater pump',
    price: 3650.0,
    description:
      'Ideal for larger residential pools, the Norsup P17X offers robust performance with a 17 kW output. It features a silent operation, advanced titanium heat exchanger, and easy-to-use touch screen controls. This model is perfect for those who value efficiency and performance during longer pool seasons.',
    specifications: [
      { name: 'Heating Capacity', value: '17 kW' },
      { name: 'Power Supply', value: '230V/50Hz (Single-phase)' },
      { name: 'COP', value: 'Up to 12.5 (depending on conditions)' },
      { name: 'Operating Temperature Range', value: '-15°C to +40°C' },
      { name: 'Refrigerant', value: 'Eco-friendly R32' },
      { name: 'Noise Level', value: '40-46 dB(A)' },
      { name: 'Heat Exchanger', value: 'Titanium' },
      { name: 'Compressor Type', value: 'Inverter Compressor' },
      { name: 'Control Interface', value: 'LCD Touch Screen' },
      { name: 'Dimensions', value: '945mm x 360mm x 735mm' },
      { name: 'Weight', value: '75 kg' },
      { name: 'Flow Rate', value: '4.5-5.0 m³/h' },
      { name: 'Wi-Fi Connectivity', value: 'Yes' },
      { name: 'Defrosting System', value: 'Reverse Cycle Defrosting' },
      {
        name: 'Warranty',
        value: '2 years product, 5 years compressor and heat exchanger',
      },
    ],
    feature: true,
    hidden: false,
  },
  {
    image: '/content/NorsupP13X.webp',
    pageLink: 'NorsupP20X',
    type: 'Product',
    category: 'Heater pump',
    price: 3995.0,
    description:
      'The most powerful in the P-Series, the Norsup P20X delivers 20 kW of heating power, making it the best option for larger pools or commercial setups. Its inverter compressor adjusts speed for maximum efficiency, and the Wi-Fi control lets you manage pool heating remotely.',
    specifications: [
      { name: 'Heating Capacity', value: '20 kW' },
      { name: 'Power Supply', value: '230V/50Hz (Single-phase)' },
      { name: 'COP', value: 'Up to 12 (depending on conditions)' },
      { name: 'Operating Temperature Range', value: '-15°C to +40°C' },
      { name: 'Refrigerant', value: 'Eco-friendly R32' },
      { name: 'Noise Level', value: '40-46 dB(A)' },
      { name: 'Heat Exchanger', value: 'Titanium' },
      { name: 'Compressor Type', value: 'Inverter Compressor' },
      { name: 'Control Interface', value: 'LCD Touch Screen' },
      { name: 'Dimensions', value: '1100mm x 400mm x 860mm' },
      { name: 'Weight', value: '95 kg' },
      { name: 'Flow Rate', value: '5.5-6.0 m³/h' },
      { name: 'Wi-Fi Connectivity', value: 'Yes' },
      { name: 'Defrosting System', value: 'Reverse Cycle Defrosting' },
      {
        name: 'Warranty',
        value: '2 years product, 5 years compressor and heat exchanger',
      },
    ],
    feature: true,
    hidden: false,
  },
  {
    image: '/content/NorsupP13X.webp',
    pageLink: 'NorsupP26X',
    type: 'Product',
    category: 'Heater pump',
    price: 4250.0, // You can adjust this price as needed
    description:
      'Designed for larger residential or commercial pools, the Norsup P26X delivers 26 kW of heating power, ensuring fast and efficient heating even in colder temperatures. Featuring a full inverter compressor and Wi-Fi control, this model offers exceptional energy savings and easy remote management. The titanium heat exchanger ensures long-lasting durability, even in saltwater pools, while the reverse cycle defrost system guarantees optimal performance year-round.',
    specifications: [
      { name: 'Heating Capacity', value: '26 kW' },
      { name: 'Power Supply', value: '230V/50Hz (Single-phase)' },
      { name: 'COP', value: 'Up to 11.8 (depending on conditions)' },
      { name: 'Operating Temperature Range', value: '-15°C to +40°C' },
      { name: 'Refrigerant', value: 'R32 refrigerant' },
      { name: 'Noise Level', value: '43-49 dB(A)' },
      { name: 'Heat Exchanger', value: 'Titanium Heat Exchanger' },
      { name: 'Compressor Type', value: 'Full Inverter Compressor' },
      { name: 'Control Interface', value: 'LCD Touch Screen' },
      { name: 'Dimensions', value: '1100mm x 400mm x 860mm' },
      { name: 'Weight', value: '100 kg' },
      { name: 'Flow Rate', value: '6.0-7.0 m³/h' },
      { name: 'Wi-Fi Connectivity', value: 'Yes' },
      { name: 'Defrosting System', value: 'Reverse Cycle Defrosting' },
      {
        name: 'Warranty',
        value: '2 years product, 5 years compressor and heat exchanger',
      },
    ],
    feature: true,
    hidden: false,
  },
];
